## Ý nghĩa các cột

| Cot                       | Y nghia                                                               |  Phan loai |
| ------------------------- | --------------------------------------------------------------------- | --------- |
| Age                |                                  |  num   |
| Gender                |                                  |  nom   |
| Cholesterol                |  nồng độ Cholesterol trong máu                            |  num   |
| BloodPressure                | huyết áp                           |  num   |
| HeartRate                | nhịp tim                        |  num   |
| BMI                | chỉ số cân nặng                    |  num   |
| Smoker                | có hút thuốc không                  |  bin   |
| Diabetes                | có bị tiểu đường không              |  bin   |
| Hypertension                | có bị tăng huyết áp  không              |  bin   |
| FamilyHistory                | có tiền sử gia đình  không              |  bin   |
| PhysicalActivity                | mức độ tập thể dục            |  numcat   |
| AlcoholConsumption                | mức độ tiêu thụ rượu            |  numcat   |
| Diet                | chất lượng bữa ăn (['Unhealthy','Moderate' 'Healthy'])         |  ord   |
| StressLevel                | mức độ căng thẳng       |  numcat   |
| Income               | thu nhập   |  num   |
| EducationLevel               | trình độ học vấn (['High School', 'College', 'Postgraduate'])  |  ord   |
| Medication               | có chữa trị trước đây chưa  |  bin   |
| ChestPainType               | loại đau ngực |  nom   |
| ECGResults               | kết quả điện tâm đồ |  nom   |
| MaxHeartRate               | nhịp tim lớn nhất |  num   |
| ST_Depression               | mức độ bất thường trong điện tâm đồ |  num   |
| ExerciseInducedAngina               | đau thắt ngực có do tập thể dục gây ra không |  bin   |
| Slope               |  |  nom   |
| NumberOfMajorVessels               | số lượng của động mạch chính  |  numcat | 
| Thalassemia               | một nhóm các bệnh di truyền về máu  |  nom | 
| PreviousHeartAttack               | có bị heart attack trước đây chưa  |  bin | 
| StrokeHistory               | có tiền sử bị đột quy không |  bin | 
| Residence               | nơi sống |  nom | 
| Outcome     | có bị đau ngực không  |  target | 

In [1]:
0.8 * 0.6 * 0.15

0.072

In [2]:
import numpy as np
import pandas as pd 

# Tạo ma trận mẫu (ví dụ: ma trận 4x4)
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# Biến ma trận thành tam giác dưới bằng cách đặt giá trị phía trên đường chéo thành 0
triangle_lower = np.tril(matrix)

a = ['a', 'b', 'c', 'd']
df = pd.DataFrame(triangle_lower, columns=a, index=a)

df

a   b   c   d
a   1   0   0   0
b   5   6   0   0
c   9  10  11   0
d  13  14  15  16

Index(['Age_num', 'Cholesterol_num', 'BloodPressure_num', 'HeartRate_num',
       'BMI_num', 'Income_num', 'MaxHeartRate_num', 'ST_Depression_num',
       'PhysicalActivity_numcat', 'AlcoholConsumption_numcat',
       'StressLevel_numcat', 'NumberOfMajorVessels_numcat', 'Smoker_bin',
       'Diabetes_bin', 'Hypertension_bin', 'FamilyHistory_bin',
       'Medication_bin', 'ExerciseInducedAngina_bin',
       'PreviousHeartAttack_bin', 'StrokeHistory_bin', 'Gender_nom',
       'ChestPainType_nom', 'ECGResults_nom', 'Slope_nom', 'Thalassemia_nom',
       'Residence_nom', 'Diet_ord', 'EducationLevel_ord', 'Outcome_target'],
      dtype='object')

cột Age_num đều 

cột Cholesterol_num đều 

cột BloodPressure_num đều 

cột HeartRate_num đều 

cột BMI_num đều 

cột Income_num đều 

cột MaxHeartRate_num đều 

cột ST_Depression_num đều 



In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_regression, mutual_info_classif

# Khởi tạo selector
selector = SelectKBest(score_func=mutual_info_classif, k="all") # Classification

# Fit cái đã
selector.fit(
    transformed_features, # features phải được transformed trước 
    target
)


# Ghi lại kết quả điểm số
feature_scores = pd.DataFrame(
    {"Feature": transformed_features.columns, "Score": selector.scores_}
).sort_values(by="Score", ascending=False)


[('a', 'b'), ('a', 'c'), ('a', 'd'), ('b', 'c'), ('b', 'd'), ('c', 'd')]


In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Các mô hình cơ bản (base learners)
base_learners = [
    ('decision_tree', DecisionTreeClassifier(max_depth=3)),
    ('svm', SVC(kernel='linear', probability=True))
]

# Mô hình học kết hợp (meta-learner)
meta_learner = LogisticRegression()

# Khởi tạo StackingClassifier
stacking_model = StackingClassifier(estimators=base_learners, final_estimator=meta_learner, cv=5)

# Tải dữ liệu mẫu
data = load_iris()
X = data.data
y = data.target

# Chia tập dữ liệu
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Huấn luyện mô hình
stacking_model.fit(X_train, y_train)

# Dự đoán trên tập kiểm tra
y_pred = stacking_model.predict(X_test)

# Tính độ chính xác
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")


Accuracy: 1.0000


In [ ]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split

# Giả sử X, y đã có
X1, X2, y1, y2 = train_test_split(X, y, test_size=0.5)

# Train lần đầu
model = LGBMClassifier(n_estimators=50, learning_rate=0.1, max_depth=3)
model.fit(X1, y1)

# Train tiếp trên X2, y2, giữ nguyên tham số
model.fit(X2, y2, init_model=model.booster_)


In [5]:
from sklearn.decomposition import KernelPCA

model = KernelPCA(n_components=0.9)

In [1]:
from lightgbm import LGBMClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# 1. Tạo dữ liệu giả
X, y = make_classification(n_samples=1000, n_features=20, random_state=42)
X1, X2, y1, y2 = train_test_split(X, y, test_size=0.5, random_state=42)

# 2. Train lần đầu
model = LGBMClassifier(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42)
model.fit(X1, y1)

# 3. In số cây hiện tại
print("Số lượng cây sau lần fit 1:", model.booster_.num_trees())

# 4. Train tiếp trên dữ liệu mới, dùng init_model
model.fit(X2, y2, init_model=model.booster_)

# 5. In số cây sau khi train tiếp
print("Số lượng cây sau lần fit 2:", model.booster_.num_trees())


[LightGBM] [Info] Number of positive: 250, number of negative: 250
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001386 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3340
[LightGBM] [Info] Number of data points in the train set: 500, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive 

In [ ]:
from xgboost import XGBClassifier

# Chia ra chạy cho đỡ RAM
X1, X2, y1, y2 = train_test_split(X, y, test_size=0.5)

# Train lần đầu
model = XGBClassifier(n_estimators=50)
model.fit(X1, y1)

model.fit(X2, y2, xgb_model=model.get_booster())

Xác suất dự đoán cho các lớp:
[[3.78468964e-03 8.27220592e-01 1.68994718e-01]
 [9.46738570e-01 5.32612296e-02 2.00200608e-07]
 [8.73019002e-09 1.55846967e-03 9.98441522e-01]
 [6.43338014e-03 7.92106296e-01 2.01460324e-01]
 [1.44094299e-03 7.74350518e-01 2.24208539e-01]
 [9.55783509e-01 4.42163143e-02 1.77062516e-07]
 [7.76129022e-02 9.08072540e-01 1.43145575e-02]
 [1.61393845e-04 1.55689752e-01 8.44148855e-01]
 [2.20749609e-03 7.62773187e-01 2.35019317e-01]
 [2.83156446e-02 9.45786638e-01 2.58977173e-02]
 [4.39625408e-04 2.43308395e-01 7.56251980e-01]
 [9.68317751e-01 3.16821713e-02 7.81652986e-08]
 [9.72944229e-01 2.70557379e-02 3.33763996e-08]
 [9.62107119e-01 3.78927703e-02 1.11058752e-07]
 [9.79275316e-01 2.07246192e-02 6.48256053e-08]
 [4.54171482e-03 7.12618594e-01 2.82839692e-01]
 [7.22701932e-06 2.42151312e-02 9.75777642e-01]
 [2.73295948e-02 9.47681419e-01 2.49889859e-02]
 [8.23128520e-03 8.31111653e-01 1.60657062e-01]
 [1.41955163e-05 3.59520213e-02 9.64033783e-01]
 [9.643765

(30, 3)

In [3]:
a = ['a', 'b', 'c', 'd']

a = a[3:10]

a

['d']

Index(['index', 'wind_kph_num', 'wind_degree_num', 'pressure_in_num',
       'humidity_num', 'cloud_num', 'visibility_km_num', 'uv_index_num',
       'gust_kph_num', 'air_quality_Carbon_Monoxide_num',
       'air_quality_Ozone_num', 'air_quality_Nitrogen_dioxide_num',
       'air_quality_Sulphur_dioxide_num', 'air_quality_PM2_5_num',
       'air_quality_PM10_num', 'moon_illumination_num', 'moon_phase_nom',
       'sunrise_ord', 'sunset_ord', 'moonrise_ord', 'moonset_ord',
       'temp_bin_target'],
      dtype='object')

cột wind_kph_num bị lệch trên 

cột wind_degree_num đều 

cột pressure_in_num bị lệch trên 

cột humidity_num đều 

cột cloud_num đều 

cột visibility_km_num bị lệch 2 bên 

cột uv_index_num đều 

cột gust_kph_num bị lệch trên 

cột air_quality_Carbon_Monoxide_num  bị lệch trên 

cột air_quality_Ozone_num bị lệch trên 

cột air_quality_Nitrogen_dioxide_num  bị lệch trên 

cột air_quality_Sulphur_dioxide_num bị lệch trên 

cột air_quality_PM2_5_num bị lệch trên 

cột air_quality_PM10_num bị lệch trên

cột moon_illumination_num đều 

In [ ]:
import pandas as pd 

a = pd.Series(['a', 'b', 'c', ''])

Hello ban nhieu nha


In [5]:
import pandas as pd

a = pd.Series(['a', 'b', 'c', 'a'])

a = a.replace({
    "a": "d"
})

a

0    d
1    b
2    c
3    d
dtype: object

| Cot                       | Y nghia                                                               | Don vi | Phan loai |
| ------------------------- | --------------------------------------------------------------------- | ------ | --------- |
| wind_kph         | Tốc độ gió (km / hour)      | none   | numeric   |
| wind_degree        | Hướng gió theo độ    | none   | numeric   |
| pressure_in         | Áp suất (inches)    | none   | numeric   |
| humidity         | Độ ẩm (%)    | none   | numeric   |
| cloud         | Phần trăm mây bao phủ (%)    | none   | numeric   |
| visibility_km         | Tầm nhìn (km)    | none   | numeric   |
| uv_index         | Chỉ số tia UV    | none   | numeric   |
| gust_kph         | sự tăng tốc đột ngột và mạnh mẽ của gió (km / h)    | none   | numeric   |
| air_quality_Carbon_Monoxide         | Nồng độ $CO$    | none   | numeric   |
| air_quality_Ozone         | Nồng độ $O_3$    | none   | numeric   |
| air_quality_Nitrogen_dioxide         | Nồng độ $NO_2$    | none   | numeric   |
| air_quality_Sulphur_dioxide         | Nồng độ $SO_2$    | none   | numeric   |
| air_quality_PM2.5         | Nồng độ $PM2.5$    | none   | numeric   |
| air_quality_PM10         | Nồng độ $PM10$    | none   | numeric   |
| sunrise         | Thời điểm mặt trời lên   | none   | ordinal   |
| sunset         | Thời điểm mặt trời lặn   | none   | ordinal   |
| moonrise         | Thời điểm trăng lên   | none   | ordinal   |
| moonset         | Thời điểm trăng lặn   | none   | ordinal   |
| moon_phase         | Pha của mặt trăng   | none   | nominal   |
| moon_illumination         | Độ sáng của mặt trăng (%)   | none   | numeric |


In [24]:
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer


a = pd.DataFrame(data={
    'a': ['b', 'b', 'c', 'daaa', 'b'],
    'b': ['01', '02', '03', '04', '01'],
    'c': [1,2,3,4,5]
})

encoder = OrdinalEncoder()
b = encoder.fit_transform(a[['a']])
encoder.categories_

[array(['b', 'c', 'daaa'], dtype=object)]

In [25]:
"feature_ordinal_dict".upper()

'FEATURE_ORDINAL_DICT'

In [1]:
"feature_ordinal_dict".upper()


'FEATURE_ORDINAL_DICT'

In [3]:
a = {

}

a = list(a.keys())

a

[]